### ISSUE TITLE
`amch export` is not working

### ISSUE THREAD

**Issue by bessarabov** [svetlyak40wt/allmychanges#12]
```
root@d94f7d4f2eb2:/app# amch export
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/amch", line 9, in <module>
    load_entry_point('allmychanges==0.6.2', 'console_scripts', 'amch')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 758, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 767, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/allmychanges/client.py", line 51, in export
    changelogs = get_changelogs(config, tracked=True)
  File "/usr/local/lib/python2.7/dist-packages/allmychanges/api.py", line 67, in get_changelogs
    return _get(config, handle + '?' + urlencode(params))
  File "/usr/local/lib/python2.7/dist-packages/allmychanges/api.py", line 57, in <lambda>
    _get = lambda *args, **kwargs: _call('get', *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/allmychanges/api.py", line 53, in _call
    raise ApiError(response.reason, response)
allmychanges.api.ApiError: INTERNAL SERVER ERROR: <h1>Server Error (500)</h1>
root@d94f7d4f2eb2:/app#
```

**Comment by bessarabov** [comment]
I'm using 

```
root@d94f7d4f2eb2:/app# pip freeze | grep allm
allmychanges==0.6.2
``

**Comment by svetlyak40wt** [comment]
@bessarabov I've fixed this 500 error on the server. The reason was that it didn't require authentication in some handle, but your token has expired.

Now amch will show authentication error. Please, regenerate your access token.

**Comment by bessarabov** [comment]
Thank you! Now `amch export` works well for me.
